## Logistic regression
- Linear classification model<br><br>
Problem: Company XYZ has launched a new SUV and based on prev data, manager wants to predict if a customer will buy this new SUV or not.<br>
Here we have age and estimated salary of customer as independent variables. Purchase is target/dependent varaible with binary value 0 and 1

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('Social_Network_Ads.csv')
data.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
# drop unnecessary column - giving no info
data = data.drop('User ID', axis=1)
data.head()

   Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [5]:
X = data.iloc[:,:-1].values
Y = data.iloc[:,-1].values

print(X.shape)
print(Y.shape)

(400, 3)
(400,)

In [6]:
print(X)

[['Male' 19 19000]
 ['Male' 35 20000]
 ['Female' 26 43000]
 ...
 ['Female' 50 20000]
 ['Male' 36 33000]
 ['Female' 49 36000]]

### check missing values

In [7]:
print(data.isnull().sum())

Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

### Splitting Dataset

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [9]:
print(X_train)

[['Male' 58 144000]
 ['Female' 59 83000]
 ['Female' 24 55000]
 ['Female' 26 35000]
 ['Female' 58 38000]
 ['Female' 42 80000]
 ['Female' 40 75000]
 ['Male' 59 130000]
 ['Female' 46 41000]
 ['Female' 41 60000]
 ['Male' 42 64000]
 ['Female' 37 146000]
 ['Female' 23 48000]
 ['Male' 25 33000]
 ['Male' 24 84000]
 ['Female' 27 96000]
 ['Male' 23 63000]
 ['Male' 48 33000]
 ['Male' 48 90000]
 ['Male' 42 104000]
 ['Female' 44 39000]
 ['Male' 32 120000]
 ['Female' 38 50000]
 ['Female' 32 135000]
 ['Female' 52 21000]
 ['Female' 53 104000]
 ['Male' 39 42000]
 ['Male' 38 61000]
 ['Female' 36 50000]
 ['Female' 36 63000]
 ['Female' 35 25000]
 ['Male' 35 50000]
 ['Male' 42 73000]
 ['Female' 47 49000]
 ['Female' 59 29000]
 ['Male' 49 65000]
 ['Female' 45 131000]
 ['Female' 31 89000]
 ['Female' 46 82000]
 ['Female' 47 51000]
 ['Male' 26 15000]
 ['Male' 60 102000]
 ['Female' 38 112000]
 ['Male' 40 107000]
 ['Female' 42 53000]
 ['Male' 35 59000]
 ['Male' 48 41000]
 ['Female' 48 134000]
 ['Female' 38 113000]
 ['Male' 29 148000]
 ['Female' 26 15000]
 ['Male' 60 42000]
 ['Male' 24 19000]
 ['Male' 42 149000]
 ['Female' 46 96000]
 ['Male' 28 59000]
 ['Male' 39 96000]
 ['Male' 28 89000]
 ['Male' 41 72000]
 ['Male' 45 26000]
 ['Female' 33 69000]
 ['Female' 20 82000]
 ['Male' 31 74000]
 ['Male' 42 80000]
 ['Female' 35 72000]
 ['Female' 33 149000]
 ['Male' 40 71000]
 ['Female' 51 146000]
 ['Male' 46 79000]
 ['Male' 35 75000]
 ['Male' 38 51000]
 ['Female' 36 75000]
 ['Female' 37 78000]
 ['Male' 38 61000]
 ['Female' 60 108000]
 ['Female' 20 82000]
 ['Male' 57 74000]
 ['Male' 42 65000]
 ['Male' 26 80000]
 ['Male' 46 117000]
 ['Male' 35 61000]
 ['Female' 21 68000]
 ['Female' 28 44000]
 ['Male' 41 87000]
 ['Female' 37 33000]
 ['Male' 27 90000]
 ['Male' 39 42000]
 ['Male' 28 123000]
 ['Female' 31 118000]
 ['Male' 25 87000]
 ['Female' 35 71000]
 ['Male' 37 70000]
 ['Male' 35 39000]
 ['Male' 47 23000]
 ['Female' 35 147000]
 ['Female' 48 138000]
 ['Male' 26 86000]
 ['Male' 25 79000]
 ['Female' 52 138000]
 ['Male' 51 23000]
 ['Female' 35 60000]
 ['Female' 33 113000]
 ['Male' 30 107000]
 ['Male' 48 33000]
 ['Female' 41 80000]
 ['Female' 48 96000]
 ['Male' 31 18000]
 ['Female' 31 71000]
 ['Male' 43 129000]
 ['Female' 59 76000]
 ['Female' 18 44000]
 ['Male' 36 118000]
 ['Female' 42 90000]
 ['Female' 47 30000]
 ['Female' 26 43000]
 ['Male' 40 78000]
 ['Male' 46 59000]
 ['Female' 59 42000]
 ['Female' 46 74000]
 ['Male' 35 91000]
 ['Female' 28 59000]
 ['Male' 40 57000]
 ['Male' 59 143000]
 ['Female' 57 26000]
 ['Female' 52 38000]
 ['Female' 47 113000]
 ['Female' 53 143000]
 ['Male' 35 27000]
 ['Female' 58 101000]
 ['Female' 45 45000]
 ['Female' 23 82000]
 ['Male' 46 23000]
 ['Male' 42 65000]
 ['Female' 28 84000]
 ['Male' 38 59000]
 ['Female' 26 84000]
 ['Female' 29 28000]
 ['Female' 37 71000]
 ['Female' 22 55000]
 ['Female' 48 35000]
 ['Male' 49 28000]
 ['Female' 38 65000]
 ['Female' 27 17000]
 ['Male' 46 28000]
 ['Male' 48 141000]
 ['Female' 26 17000]
 ['Female' 35 97000]
 ['Female' 39 59000]
 ['Female' 24 27000]
 ['Male' 32 18000]
 ['Male' 46 88000]
 ['Male' 35 58000]
 ['Male' 56 60000]
 ['Male' 47 34000]
 ['Female' 40 72000]
 ['Male' 32 100000]
 ['Female' 19 21000]
 ['Male' 25 90000]
 ['Male' 35 88000]
 ['Male' 28 32000]
 ['Female' 50 20000]
 ['Male' 40 59000]
 ['Female' 50 44000]
 ['Male' 35 72000]
 ['Female' 40 142000]
 ['Female' 46 32000]
 ['Female' 39 71000]
 ['Male' 20 74000]
 ['Male' 29 75000]
 ['Male' 31 76000]
 ['Male' 47 25000]
 ['Male' 40 61000]
 ['Male' 34 112000]
 ['Female' 38 80000]
 ['Female' 42 75000]
 ['Female' 47 47000]
 ['Female' 39 75000]
 ['Male' 19 25000]
 ['Female' 37 80000]
 ['Male' 36 60000]
 ['Male' 41 52000]
 ['Male' 36 125000]
 ['Female' 48 29000]
 ['Female' 36 126000]
 ['Female' 51 134000]
 ['Female' 27 57000]
 ['Male' 38 71000]
 ['Female' 39 61000]
 ['Female' 22 27000]
 ['Female' 33 60000]
 ['Male' 48 74000]
 ['Female' 58 23000]
 ['Male' 53 72000]
 ['Female' 32 117000]
 ['Male' 54 70000]
 ['Male' 30 80000]
 ['Female' 58 95000]
 ['Female' 26 52000]
 ['Male' 45 79000]
 ['Male' 24 55000]
 ['Male' 40 75000]
 ['Female' 33 28000]
 ['Female' 44 139000]
 ['Male' 22 18000]
 ['Female' 33 51000]
 ['Female' 43 133000]
 ['Female' 24 32000]
 ['Female' 46 22000]
 ['Male' 35 55000]
 ['Female' 54 104000]
 ['Female' 48 119000]
 ['Male' 35 53000]
 ['Male' 37 144000]
 ['Female' 23 66000]
 ['Female' 37 137000]
 ['Male' 31 58000]
 ['Female' 33 41000]
 ['Female' 45 22000]
 ['Male' 30 15000]
 ['Male' 19 19000]
 ['Male' 49 74000]
 ['Male' 39 122000]
 ['Male' 35 73000]
 ['Male' 39 71000]
 ['Male' 24 23000]
 ['Female' 41 72000]
 ['Female' 29 83000]
 ['Female' 54 26000]
 ['Female' 35 44000]
 ['Male' 37 75000]
 ['Female' 29 47000]
 ['Female' 31 68000]
 ['Male' 42 54000]
 ['Male' 30 135000]
 ['Female' 52 114000]
 ['Female' 50 36000]
 ['Male' 56 133000]
 ['Male' 29 61000]
 ['Male' 30 89000]
 ['Male' 26 16000]
 ['Male' 33 31000]
 ['Female' 41 72000]
 ['Male' 36 33000]
 ['Female' 55 125000]
 ['Female' 48 131000]
 ['Female' 41 71000]
 ['Female' 30 62000]
 ['Male' 37 72000]
 ['Female' 41 63000]
 ['Female' 58 47000]
 ['Female' 30 116000]
 ['Male' 20 49000]
 ['Male' 37 74000]
 ['Male' 41 59000]
 ['Male' 49 89000]
 ['Male' 28 79000]
 ['Female' 53 82000]
 ['Male' 40 57000]
 ['Male' 60 34000]
 ['Male' 35 108000]
 ['Male' 21 72000]
 ['Male' 38 71000]
 ['Male' 39 106000]
 ['Female' 37 57000]
 ['Female' 26 72000]
 ['Female' 35 23000]
 ['Female' 54 108000]
 ['Male' 30 17000]
 ['Male' 39 134000]
 ['Male' 29 43000]
 ['Male' 33 43000]
 ['Male' 35 38000]
 ['Male' 41 45000]
 ['Female' 41 72000]
 ['Female' 39 134000]
 ['Female' 27 137000]
 ['Female' 21 16000]
 ['Male' 26 32000]
 ['Male' 31 66000]
 ['Female' 39 73000]
 ['Male' 41 79000]
 ['Female' 47 50000]
 ['Female' 41 30000]
 ['Female' 37 93000]
 ['Female' 60 46000]
 ['Male' 25 22000]
 ['Female' 28 37000]
 ['Female' 38 55000]
 ['Female' 36 54000]
 ['Female' 20 36000]
 ['Female' 56 104000]
 ['Male' 40 57000]
 ['Female' 42 108000]
 ['Female' 20 23000]
 ['Male' 40 65000]
 ['Male' 47 20000]
 ['Female' 18 86000]
 ['Male' 35 79000]
 ['Female' 57 33000]
 ['Female' 34 72000]
 ['Female' 49 39000]
 ['Female' 27 31000]
 ['Male' 19 70000]
 ['Female' 39 79000]
 ['Male' 26 81000]
 ['Male' 25 80000]
 ['Female' 28 85000]
 ['Male' 55 39000]
 ['Female' 50 88000]
 ['Male' 49 88000]
 ['Male' 52 150000]
 ['Female' 35 65000]
 ['Male' 42 54000]
 ['Male' 34 43000]
 ['Male' 37 52000]
 ['Female' 48 30000]
 ['Male' 29 43000]
 ['Male' 36 52000]
 ['Female' 27 54000]
 ['Female' 26 118000]]

In [10]:
print(X_train.shape)
print(X_test.shape)

(320, 3)
(80, 3)

### Categorical column encoding

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64
 2   EstimatedSalary  400 non-null    int64
 3   Purchased        400 non-null    int64
dtypes: int64(3), object(1)
memory usage: 12.6+ KB

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

CT = ColumnTransformer(
    transformers = [
        ('encoder', OneHotEncoder(drop='first', sparse=False), [0])
    ],
    remainder = 'passthrough'
)

fit_transform done on training data, while transform done on test dataset

In [13]:
X_train = CT.fit_transform(X_train)
X_test = CT.transform(X_test)

c:\Users\gusai\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [14]:
print(X_train)

[[1.0 58 144000]
 [0.0 59 83000]
 [0.0 24 55000]
 [0.0 26 35000]
 [0.0 58 38000]
 [0.0 42 80000]
 [0.0 40 75000]
 [1.0 59 130000]
 [0.0 46 41000]
 [0.0 41 60000]
 [1.0 42 64000]
 [0.0 37 146000]
 [0.0 23 48000]
 [1.0 25 33000]
 [1.0 24 84000]
 [0.0 27 96000]
 [1.0 23 63000]
 [1.0 48 33000]
 [1.0 48 90000]
 [1.0 42 104000]
 [0.0 44 39000]
 [1.0 32 120000]
 [0.0 38 50000]
 [0.0 32 135000]
 [0.0 52 21000]
 [0.0 53 104000]
 [1.0 39 42000]
 [1.0 38 61000]
 [0.0 36 50000]
 [0.0 36 63000]
 [0.0 35 25000]
 [1.0 35 50000]
 [1.0 42 73000]
 [0.0 47 49000]
 [0.0 59 29000]
 [1.0 49 65000]
 [0.0 45 131000]
 [0.0 31 89000]
 [0.0 46 82000]
 [0.0 47 51000]
 [1.0 26 15000]
 [1.0 60 102000]
 [0.0 38 112000]
 [1.0 40 107000]
 [0.0 42 53000]
 [1.0 35 59000]
 [1.0 48 41000]
 [0.0 48 134000]
 [0.0 38 113000]
 [1.0 29 148000]
 [0.0 26 15000]
 [1.0 60 42000]
 [1.0 24 19000]
 [1.0 42 149000]
 [0.0 46 96000]
 [1.0 28 59000]
 [1.0 39 96000]
 [1.0 28 89000]
 [1.0 41 72000]
 [1.0 45 26000]
 [0.0 33 69000]
 [0.0 20 82000]
 [1.0 31 74000]
 [1.0 42 80000]
 [0.0 35 72000]
 [0.0 33 149000]
 [1.0 40 71000]
 [0.0 51 146000]
 [1.0 46 79000]
 [1.0 35 75000]
 [1.0 38 51000]
 [0.0 36 75000]
 [0.0 37 78000]
 [1.0 38 61000]
 [0.0 60 108000]
 [0.0 20 82000]
 [1.0 57 74000]
 [1.0 42 65000]
 [1.0 26 80000]
 [1.0 46 117000]
 [1.0 35 61000]
 [0.0 21 68000]
 [0.0 28 44000]
 [1.0 41 87000]
 [0.0 37 33000]
 [1.0 27 90000]
 [1.0 39 42000]
 [1.0 28 123000]
 [0.0 31 118000]
 [1.0 25 87000]
 [0.0 35 71000]
 [1.0 37 70000]
 [1.0 35 39000]
 [1.0 47 23000]
 [0.0 35 147000]
 [0.0 48 138000]
 [1.0 26 86000]
 [1.0 25 79000]
 [0.0 52 138000]
 [1.0 51 23000]
 [0.0 35 60000]
 [0.0 33 113000]
 [1.0 30 107000]
 [1.0 48 33000]
 [0.0 41 80000]
 [0.0 48 96000]
 [1.0 31 18000]
 [0.0 31 71000]
 [1.0 43 129000]
 [0.0 59 76000]
 [0.0 18 44000]
 [1.0 36 118000]
 [0.0 42 90000]
 [0.0 47 30000]
 [0.0 26 43000]
 [1.0 40 78000]
 [1.0 46 59000]
 [0.0 59 42000]
 [0.0 46 74000]
 [1.0 35 91000]
 [0.0 28 59000]
 [1.0 40 57000]
 [1.0 59 143000]
 [0.0 57 26000]
 [0.0 52 38000]
 [0.0 47 113000]
 [0.0 53 143000]
 [1.0 35 27000]
 [0.0 58 101000]
 [0.0 45 45000]
 [0.0 23 82000]
 [1.0 46 23000]
 [1.0 42 65000]
 [0.0 28 84000]
 [1.0 38 59000]
 [0.0 26 84000]
 [0.0 29 28000]
 [0.0 37 71000]
 [0.0 22 55000]
 [0.0 48 35000]
 [1.0 49 28000]
 [0.0 38 65000]
 [0.0 27 17000]
 [1.0 46 28000]
 [1.0 48 141000]
 [0.0 26 17000]
 [0.0 35 97000]
 [0.0 39 59000]
 [0.0 24 27000]
 [1.0 32 18000]
 [1.0 46 88000]
 [1.0 35 58000]
 [1.0 56 60000]
 [1.0 47 34000]
 [0.0 40 72000]
 [1.0 32 100000]
 [0.0 19 21000]
 [1.0 25 90000]
 [1.0 35 88000]
 [1.0 28 32000]
 [0.0 50 20000]
 [1.0 40 59000]
 [0.0 50 44000]
 [1.0 35 72000]
 [0.0 40 142000]
 [0.0 46 32000]
 [0.0 39 71000]
 [1.0 20 74000]
 [1.0 29 75000]
 [1.0 31 76000]
 [1.0 47 25000]
 [1.0 40 61000]
 [1.0 34 112000]
 [0.0 38 80000]
 [0.0 42 75000]
 [0.0 47 47000]
 [0.0 39 75000]
 [1.0 19 25000]
 [0.0 37 80000]
 [1.0 36 60000]
 [1.0 41 52000]
 [1.0 36 125000]
 [0.0 48 29000]
 [0.0 36 126000]
 [0.0 51 134000]
 [0.0 27 57000]
 [1.0 38 71000]
 [0.0 39 61000]
 [0.0 22 27000]
 [0.0 33 60000]
 [1.0 48 74000]
 [0.0 58 23000]
 [1.0 53 72000]
 [0.0 32 117000]
 [1.0 54 70000]
 [1.0 30 80000]
 [0.0 58 95000]
 [0.0 26 52000]
 [1.0 45 79000]
 [1.0 24 55000]
 [1.0 40 75000]
 [0.0 33 28000]
 [0.0 44 139000]
 [1.0 22 18000]
 [0.0 33 51000]
 [0.0 43 133000]
 [0.0 24 32000]
 [0.0 46 22000]
 [1.0 35 55000]
 [0.0 54 104000]
 [0.0 48 119000]
 [1.0 35 53000]
 [1.0 37 144000]
 [0.0 23 66000]
 [0.0 37 137000]
 [1.0 31 58000]
 [0.0 33 41000]
 [0.0 45 22000]
 [1.0 30 15000]
 [1.0 19 19000]
 [1.0 49 74000]
 [1.0 39 122000]
 [1.0 35 73000]
 [1.0 39 71000]
 [1.0 24 23000]
 [0.0 41 72000]
 [0.0 29 83000]
 [0.0 54 26000]
 [0.0 35 44000]
 [1.0 37 75000]
 [0.0 29 47000]
 [0.0 31 68000]
 [1.0 42 54000]
 [1.0 30 135000]
 [0.0 52 114000]
 [0.0 50 36000]
 [1.0 56 133000]
 [1.0 29 61000]
 [1.0 30 89000]
 [1.0 26 16000]
 [1.0 33 31000]
 [0.0 41 72000]
 [1.0 36 33000]
 [0.0 55 125000]
 [0.0 48 131000]
 [0.0 41 71000]
 [0.0 30 62000]
 [1.0 37 72000]
 [0.0 41 63000]
 [0.0 58 47000]
 [0.0 30 116000]
 [1.0 20 49000]
 [1.0 37 74000]
 [1.0 41 59000]
 [1.0 49 89000]
 [1.0 28 79000]
 [0.0 53 82000]
 [1.0 40 57000]
 [1.0 60 34000]
 [1.0 35 108000]
 [1.0 21 72000]
 [1.0 38 71000]
 [1.0 39 106000]
 [0.0 37 57000]
 [0.0 26 72000]
 [0.0 35 23000]
 [0.0 54 108000]
 [1.0 30 17000]
 [1.0 39 134000]
 [1.0 29 43000]
 [1.0 33 43000]
 [1.0 35 38000]
 [1.0 41 45000]
 [0.0 41 72000]
 [0.0 39 134000]
 [0.0 27 137000]
 [0.0 21 16000]
 [1.0 26 32000]
 [1.0 31 66000]
 [0.0 39 73000]
 [1.0 41 79000]
 [0.0 47 50000]
 [0.0 41 30000]
 [0.0 37 93000]
 [0.0 60 46000]
 [1.0 25 22000]
 [0.0 28 37000]
 [0.0 38 55000]
 [0.0 36 54000]
 [0.0 20 36000]
 [0.0 56 104000]
 [1.0 40 57000]
 [0.0 42 108000]
 [0.0 20 23000]
 [1.0 40 65000]
 [1.0 47 20000]
 [0.0 18 86000]
 [1.0 35 79000]
 [0.0 57 33000]
 [0.0 34 72000]
 [0.0 49 39000]
 [0.0 27 31000]
 [1.0 19 70000]
 [0.0 39 79000]
 [1.0 26 81000]
 [1.0 25 80000]
 [0.0 28 85000]
 [1.0 55 39000]
 [0.0 50 88000]
 [1.0 49 88000]
 [1.0 52 150000]
 [0.0 35 65000]
 [1.0 42 54000]
 [1.0 34 43000]
 [1.0 37 52000]
 [0.0 48 30000]
 [1.0 29 43000]
 [1.0 36 52000]
 [0.0 27 54000]
 [0.0 26 118000]]

### Feature scaling

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

Scale all column except first, as it is category column and scaling it will loose it's meaning.<br>
Also apply fit_transform on X_train and only on X_test to avoid data leakage.

In [16]:
X_train[:, 1:] = scaler.fit_transform(X_train[:, 1:])
X_test[:, 1:] = scaler.transform(X_test[:, 1:])

In [17]:
print(X_train)

[[1.0 1.9229500774458068 2.146015658291428]
 [0.0 2.020160823856969 0.37871929707771346]
 [0.0 -1.3822153005337159 -0.43249870479087665]
 [0.0 -1.187793807711391 -1.0119401346970125]
 [0.0 1.9229500774458068 -0.9250239202110921]
 [0.0 0.3675781348672079 0.29180308259179305]
 [0.0 0.17315664204488307 0.14694272511525913]
 [1.0 2.020160823856969 1.7404066573571326]
 [0.0 0.7564211205118576 -0.8381077057251717]
 [0.0 0.2703673884560455 -0.28763834731434273]
 [1.0 0.3675781348672079 -0.17175006133311557]
 [0.0 -0.11847559718860422 2.2039598012820414]
 [0.0 -1.4794260469448783 -0.6353032052580242]
 [1.0 -1.2850045541225534 -1.069884277687626]
 [1.0 -1.3822153005337159 0.40769136857302024]
 [0.0 -1.0905830613002285 0.7553562265167018]
 [1.0 -1.4794260469448783 -0.20072213282842236]
 [1.0 0.9508426133341825 -1.069884277687626]
 [1.0 0.9508426133341825 0.5815237975448609]
 [1.0 0.3675781348672079 0.987132798479156]
 [0.0 0.5619996276895328 -0.8960518487157852]
 [1.0 -0.6045293292444164 1.4506859424040646]
 [0.0 -0.021264850777441783 -0.5773590622674106]
 [0.0 -0.6045293292444164 1.8852670148336665]
 [0.0 1.3396855989788323 -1.4175491356313075]
 [0.0 1.4368963453899948 0.987132798479156]
 [1.0 0.07594589563372064 -0.8091356342298649]
 [1.0 -0.021264850777441783 -0.25866627581903595]
 [0.0 -0.21568634359976666 -0.5773590622674106]
 [0.0 -0.21568634359976666 -0.20072213282842236]
 [0.0 -0.3128970900109291 -1.3016608496500803]
 [1.0 -0.3128970900109291 -0.5773590622674106]
 [1.0 0.3675781348672079 0.08899858212464555]
 [0.0 0.8536318669230201 -0.6063311337627174]
 [0.0 2.020160823856969 -1.1857725636688532]
 [1.0 1.048053359745345 -0.14277798983780876]
 [0.0 0.6592103741006953 1.7693787288524394]
 [0.0 -0.7017400756555788 0.5525517260495542]
 [0.0 0.7564211205118576 0.3497472255824067]
 [0.0 0.8536318669230201 -0.5483869907721038]
 [1.0 -1.187793807711391 -1.5913815646031482]
 [1.0 2.1173715702681317 0.9291886554885425]
 [0.0 -0.021264850777441783 1.2189093704416103]
 [1.0 0.17315664204488307 1.0740490129650764]
 [0.0 0.3675781348672079 -0.4904428477814902]
 [1.0 -0.3128970900109291 -0.3166104188096495]
 [1.0 0.9508426133341825 -0.8381077057251717]
 [0.0 0.9508426133341825 1.8562949433383598]
 [0.0 -0.021264850777441783 1.247881441936917]
 [1.0 -0.8961615684779036 2.261903944272655]
 [0.0 -1.187793807711391 -1.5913815646031482]
 [1.0 2.1173715702681317 -0.8091356342298649]
 [1.0 -1.3822153005337159 -1.475493278621921]
 [1.0 0.3675781348672079 2.2908760157679615]
 [0.0 0.7564211205118576 0.7553562265167018]
 [1.0 -0.9933723148890661 -0.3166104188096495]
 [1.0 0.07594589563372064 0.7553562265167018]
 [1.0 -0.9933723148890661 0.5525517260495542]
 [1.0 0.2703673884560455 0.06002651062933875]
 [1.0 0.6592103741006953 -1.2726887781547735]
 [0.0 -0.5073185828332539 -0.026889703856581616]
 [0.0 -1.7710582861783655 0.3497472255824067]
 [1.0 -0.7017400756555788 0.11797065361995233]
 [1.0 0.3675781348672079 0.29180308259179305]
 [0.0 -0.3128970900109291 0.06002651062933875]
 [0.0 -0.5073185828332539 2.2908760157679615]
 [1.0 0.17315664204488307 0.031054439134031966]
 [0.0 1.2424748525676699 2.2039598012820414]
 [1.0 0.7564211205118576 0.26283101109648627]
 [1.0 -0.3128970900109291 0.14694272511525913]
 [1.0 -0.021264850777441783 -0.5483869907721038]
 [0.0 -0.21568634359976666 0.14694272511525913]
 [0.0 -0.11847559718860422 0.23385893960117948]
 [1.0 -0.021264850777441783 -0.25866627581903595]
 [0.0 2.1173715702681317 1.1030210844603832]
 [0.0 -1.7710582861783655 0.3497472255824067]
 [1.0 1.8257393310346444 0.11797065361995233]
 [1.0 0.3675781348672079 -0.14277798983780876]
 [1.0 -1.187793807711391 0.29180308259179305]
 [1.0 0.7564211205118576 1.3637697279181442]
 [1.0 -0.3128970900109291 -0.25866627581903595]
 [0.0 -1.673847539767203 -0.0558617753518884]
 [0.0 -0.9933723148890661 -0.7511914912392513]
 [1.0 0.2703673884560455 0.4946075830589406]
 [0.0 -0.11847559718860422 -1.069884277687626]
 [1.0 -1.0905830613002285 0.5815237975448609]
 [1.0 0.07594589563372064 -0.8091356342298649]
 [1.0 -0.9933723148890661 1.537602156889985]
 [0.0 -0.7017400756555788 1.392741799413451]
 [1.0 -1.2850045541225534 0.4946075830589406]
 [0.0 -0.3128970900109291 0.031054439134031966]
 [1.0 -0.11847559718860422 0.0020823676387251755]
 [1.0 -0.3128970900109291 -0.8960518487157852]
 [1.0 0.8536318669230201 -1.359604992640694]
 [0.0 -0.3128970900109291 2.232931872777348]
 [0.0 0.9508426133341825 1.972183229319587]
 [1.0 -1.187793807711391 0.4656355115636338]
 [1.0 -1.2850045541225534 0.26283101109648627]
 [0.0 1.3396855989788323 1.972183229319587]
 [1.0 1.2424748525676699 -1.359604992640694]
 [0.0 -0.3128970900109291 -0.28763834731434273]
 [0.0 -0.5073185828332539 1.247881441936917]
 [1.0 -0.7989508220667412 1.0740490129650764]
 [1.0 0.9508426133341825 -1.069884277687626]
 [0.0 0.2703673884560455 0.29180308259179305]
 [0.0 0.9508426133341825 0.7553562265167018]
 [1.0 -0.7017400756555788 -1.5044653501172278]
 [0.0 -0.7017400756555788 0.031054439134031966]
 [1.0 0.46478888127837037 1.7114345858618258]
 [0.0 2.020160823856969 0.17591479661056592]
 [0.0 -1.9654797790006904 -0.7511914912392513]
 [1.0 -0.21568634359976666 1.392741799413451]
 [0.0 0.3675781348672079 0.5815237975448609]
 [0.0 0.8536318669230201 -1.1568004921735464]
 [0.0 -1.187793807711391 -0.7801635627345581]
 [1.0 0.17315664204488307 0.23385893960117948]
 [1.0 0.7564211205118576 -0.3166104188096495]
 [0.0 2.020160823856969 -0.8091356342298649]
 [0.0 0.7564211205118576 0.11797065361995233]
 [1.0 -0.3128970900109291 0.6104958690401677]
 [0.0 -0.9933723148890661 -0.3166104188096495]
 [1.0 0.17315664204488307 -0.3745545618002631]
 [1.0 2.020160823856969 2.117043586796121]
 [0.0 1.8257393310346444 -1.2726887781547735]
 [0.0 1.3396855989788323 -0.9250239202110921]
 [0.0 0.8536318669230201 1.247881441936917]
 [0.0 1.4368963453899948 2.117043586796121]
 [1.0 -0.3128970900109291 -1.2437167066594668]
 [0.0 1.9229500774458068 0.9002165839932357]
 [0.0 0.6592103741006953 -0.7222194197439445]
 [0.0 -1.4794260469448783 0.3497472255824067]
 [1.0 0.7564211205118576 -1.359604992640694]
 [1.0 0.3675781348672079 -0.14277798983780876]
 [0.0 -0.9933723148890661 0.40769136857302024]
 [1.0 -0.021264850777441783 -0.3166104188096495]
 [0.0 -1.187793807711391 0.40769136857302024]
 [0.0 -0.8961615684779036 -1.21474463516416]
 [0.0 -0.11847559718860422 0.031054439134031966]
 [0.0 -1.5766367933560406 -0.43249870479087665]
 [0.0 0.9508426133341825 -1.0119401346970125]
 [1.0 1.048053359745345 -1.21474463516416]
 [0.0 -0.021264850777441783 -0.14277798983780876]
 [0.0 -1.0905830613002285 -1.5334374216125346]
 [1.0 0.7564211205118576 -1.21474463516416]
 [1.0 0.9508426133341825 2.0590994438055072]
 [0.0 -1.187793807711391 -1.5334374216125346]
 [0.0 -0.3128970900109291 0.7843282980120085]
 [0.0 0.07594589563372064 -0.3166104188096495]
 [0.0 -1.3822153005337159 -1.2437167066594668]
 [1.0 -0.6045293292444164 -1.5044653501172278]
 [1.0 0.7564211205118576 0.5235796545542474]
 [1.0 -0.3128970900109291 -0.3455824903049563]
 [1.0 1.728528584623482 -0.28763834731434273]
 [1.0 0.8536318669230201 -1.0409122061923193]
 [0.0 0.17315664204488307 0.06002651062933875]
 [1.0 -0.6045293292444164 0.8712445124979289]
 [0.0 -1.868269032589528 -1.4175491356313075]
 [1.0 -1.2850045541225534 0.5815237975448609]
 [1.0 -0.3128970900109291 0.5235796545542474]
 [1.0 -0.9933723148890661 -1.0988563491829328]
 [0.0 1.1452641061565074 -1.4465212071266143]
 [1.0 0.17315664204488307 -0.3166104188096495]
 [0.0 1.1452641061565074 -0.7511914912392513]
 [1.0 -0.3128970900109291 0.06002651062933875]
 [0.0 0.17315664204488307 2.088071515300814]
 [0.0 0.7564211205118576 -1.0988563491829328]
 [0.0 0.07594589563372064 0.031054439134031966]
 [1.0 -1.7710582861783655 0.11797065361995233]
 [1.0 -0.8961615684779036 0.14694272511525913]
 [1.0 -0.7017400756555788 0.17591479661056592]
 [1.0 0.8536318669230201 -1.3016608496500803]
 [1.0 0.17315664204488307 -0.25866627581903595]
 [1.0 -0.41010783642209153 1.2189093704416103]
 [0.0 -0.021264850777441783 0.29180308259179305]
 [0.0 0.3675781348672079 0.14694272511525913]
 [0.0 0.8536318669230201 -0.664275276753331]
 [0.0 0.07594589563372064 0.14694272511525913]
 [1.0 -1.868269032589528 -1.3016608496500803]
 [0.0 -0.11847559718860422 0.29180308259179305]
 [1.0 -0.21568634359976666 -0.28763834731434273]
 [1.0 0.2703673884560455 -0.5194149192767971]
 [1.0 -0.21568634359976666 1.5955462998805987]
 [0.0 0.9508426133341825 -1.1857725636688532]
 [0.0 -0.21568634359976666 1.6245183713759055]
 [0.0 1.2424748525676699 1.8562949433383598]
 [0.0 -1.0905830613002285 -0.3745545618002631]
 [1.0 -0.021264850777441783 0.031054439134031966]
 [0.0 0.07594589563372064 -0.25866627581903595]
 [0.0 -1.5766367933560406 -1.2437167066594668]
 [0.0 -0.5073185828332539 -0.28763834731434273]
 [1.0 0.9508426133341825 0.11797065361995233]
 [0.0 1.9229500774458068 -1.359604992640694]
 [1.0 1.4368963453899948 0.06002651062933875]
 [0.0 -0.6045293292444164 1.3637697279181442]
 [1.0 1.534107091801157 0.0020823676387251755]
 [1.0 -0.7989508220667412 0.29180308259179305]
 [0.0 1.9229500774458068 0.7263841550213949]
 [0.0 -1.187793807711391 -0.5194149192767971]
 [1.0 0.6592103741006953 0.26283101109648627]
 [1.0 -1.3822153005337159 -0.43249870479087665]
 [1.0 0.17315664204488307 0.14694272511525913]
 [0.0 -0.5073185828332539 -1.21474463516416]
 [0.0 0.5619996276895328 2.0011553008148937]
 [1.0 -1.5766367933560406 -1.5044653501172278]
 [0.0 -0.5073185828332539 -0.5483869907721038]
 [0.0 0.46478888127837037 1.827322871843053]
 [0.0 -1.3822153005337159 -1.0988563491829328]
 [0.0 0.7564211205118576 -1.3885770641360007]
 [1.0 -0.3128970900109291 -0.43249870479087665]
 [0.0 1.534107091801157 0.987132798479156]
 [0.0 0.9508426133341825 1.4217138709087578]
 [1.0 -0.3128970900109291 -0.4904428477814902]
 [1.0 -0.11847559718860422 2.146015658291428]
 [0.0 -1.4794260469448783 -0.11380591834250198]
 [0.0 -0.11847559718860422 1.94321115782428]
 [1.0 -0.7017400756555788 -0.3455824903049563]
 [0.0 -0.5073185828332539 -0.8381077057251717]
 [0.0 0.6592103741006953 -1.3885770641360007]
 [1.0 -0.7989508220667412 -1.5913815646031482]
 [1.0 -1.868269032589528 -1.475493278621921]
 [1.0 1.048053359745345 0.11797065361995233]
 [1.0 0.07594589563372064 1.5086300853946781]
 [1.0 -0.3128970900109291 0.08899858212464555]
 [1.0 0.07594589563372064 0.031054439134031966]
 [1.0 -1.3822153005337159 -1.359604992640694]
 [0.0 0.2703673884560455 0.06002651062933875]
 [0.0 -0.8961615684779036 0.37871929707771346]
 [0.0 1.534107091801157 -1.2726887781547735]
 [0.0 -0.3128970900109291 -0.7511914912392513]
 [1.0 -0.11847559718860422 0.14694272511525913]
 [0.0 -0.8961615684779036 -0.664275276753331]
 [0.0 -0.7017400756555788 -0.0558617753518884]
 [1.0 0.3675781348672079 -0.46147077628618344]
 [1.0 -0.7989508220667412 1.8852670148336665]
 [0.0 1.3396855989788323 1.2768535134322239]
 [0.0 1.1452641061565074 -0.9829680632017057]
 [1.0 1.728528584623482 1.827322871843053]
 [1.0 -0.8961615684779036 -0.25866627581903595]
 [1.0 -0.7989508220667412 0.5525517260495542]
 [1.0 -1.187793807711391 -1.5624094931078414]
 [1.0 -0.5073185828332539 -1.1278284206782396]
 [0.0 0.2703673884560455 0.06002651062933875]
 [1.0 -0.21568634359976666 -1.069884277687626]
 [0.0 1.6313178382123195 1.5955462998805987]
 [0.0 0.9508426133341825 1.7693787288524394]
 [0.0 0.2703673884560455 0.031054439134031966]
 [0.0 -0.7989508220667412 -0.22969420432372914]
 [1.0 -0.11847559718860422 0.06002651062933875]
 [0.0 0.2703673884560455 -0.20072213282842236]
 [0.0 1.9229500774458068 -0.664275276753331]
 [0.0 -0.7989508220667412 1.3347976564228374]
 [1.0 -1.7710582861783655 -0.6063311337627174]
 [1.0 -0.11847559718860422 0.11797065361995233]
 [1.0 0.2703673884560455 -0.3166104188096495]
 [1.0 1.048053359745345 0.5525517260495542]
 [1.0 -0.9933723148890661 0.26283101109648627]
 [0.0 1.4368963453899948 0.3497472255824067]
 [1.0 0.17315664204488307 -0.3745545618002631]
 [1.0 2.1173715702681317 -1.0409122061923193]
 [1.0 -0.3128970900109291 1.1030210844603832]
 [1.0 -1.673847539767203 0.06002651062933875]
 [1.0 -0.021264850777441783 0.031054439134031966]
 [1.0 0.07594589563372064 1.0450769414697696]
 [0.0 -0.11847559718860422 -0.3745545618002631]
 [0.0 -1.187793807711391 0.06002651062933875]
 [0.0 -0.3128970900109291 -1.359604992640694]
 [0.0 1.534107091801157 1.1030210844603832]
 [1.0 -0.7989508220667412 -1.5334374216125346]
 [1.0 0.07594589563372064 1.8562949433383598]
 [1.0 -0.8961615684779036 -0.7801635627345581]
 [1.0 -0.5073185828332539 -0.7801635627345581]
 [1.0 -0.3128970900109291 -0.9250239202110921]
 [1.0 0.2703673884560455 -0.7222194197439445]
 [0.0 0.2703673884560455 0.06002651062933875]
 [0.0 0.07594589563372064 1.8562949433383598]
 [0.0 -1.0905830613002285 1.94321115782428]
 [0.0 -1.673847539767203 -1.5624094931078414]
 [1.0 -1.187793807711391 -1.0988563491829328]
 [1.0 -0.7017400756555788 -0.11380591834250198]
 [0.0 0.07594589563372064 0.08899858212464555]
 [1.0 0.2703673884560455 0.26283101109648627]
 [0.0 0.8536318669230201 -0.5773590622674106]
 [0.0 0.2703673884560455 -1.1568004921735464]
 [0.0 -0.11847559718860422 0.6684400120307813]
 [0.0 2.1173715702681317 -0.6932473482486378]
 [1.0 -1.2850045541225534 -1.3885770641360007]
 [0.0 -0.9933723148890661 -0.9539959917063989]
 [0.0 -0.021264850777441783 -0.43249870479087665]
 [0.0 -0.21568634359976666 -0.46147077628618344]
 [0.0 -1.7710582861783655 -0.9829680632017057]
 [0.0 1.728528584623482 0.987132798479156]
 [1.0 0.17315664204488307 -0.3745545618002631]
 [0.0 0.3675781348672079 1.1030210844603832]
 [0.0 -1.7710582861783655 -1.359604992640694]
 [1.0 0.17315664204488307 -0.14277798983780876]
 [1.0 0.8536318669230201 -1.4465212071266143]
 [0.0 -1.9654797790006904 0.4656355115636338]
 [1.0 -0.3128970900109291 0.26283101109648627]
 [0.0 1.8257393310346444 -1.069884277687626]
 [0.0 -0.41010783642209153 0.06002651062933875]
 [0.0 1.048053359745345 -0.8960518487157852]
 [0.0 -1.0905830613002285 -1.1278284206782396]
 [1.0 -1.868269032589528 0.0020823676387251755]
 [0.0 0.07594589563372064 0.26283101109648627]
 [1.0 -1.187793807711391 0.32077515408709983]
 [1.0 -1.2850045541225534 0.29180308259179305]
 [0.0 -0.9933723148890661 0.436663440068327]
 [1.0 1.6313178382123195 -0.8960518487157852]
 [0.0 1.1452641061565074 0.5235796545542474]
 [1.0 1.048053359745345 0.5235796545542474]
 [1.0 1.3396855989788323 2.3198480872632685]
 [0.0 -0.3128970900109291 -0.14277798983780876]
 [1.0 0.3675781348672079 -0.46147077628618344]
 [1.0 -0.41010783642209153 -0.7801635627345581]
 [1.0 -0.11847559718860422 -0.5194149192767971]
 [0.0 0.9508426133341825 -1.1568004921735464]
 [1.0 -0.8961615684779036 -0.7801635627345581]
 [1.0 -0.21568634359976666 -0.5194149192767971]
 [0.0 -1.0905830613002285 -0.46147077628618344]
 [0.0 -1.187793807711391 1.392741799413451]]

### Training Logistic Regression model

In [18]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, Y_train)

LogisticRegression()

In [19]:
# predicting test set results
y_pred = classifier.predict(X_test)
print(y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 1 0 1 1]

### Predict new data
- predict if a female customer of age 27 with salary 97000 will buy the new SUV car or not

- new data must be passed in same way as it is trained

In [20]:
# new_data = pd.DataFrame(
#     [['Female', 27, 97000]],
#     columns=['Gender', 'Age', 'EstimatedSalary']  # must match your training columns
# )
# print(new_data)

new_data = np.array([['Female', 27, 97000]], dtype=object)
print(new_data)

[['Female' 27 97000]]

In [21]:
new_data_encoded = CT.transform(new_data)
print(new_data_encoded)

[[0.0 27 97000]]

In [23]:
# scale it
scaled_data = scaler.transform(new_data_encoded[:,1:])
print(scaled_data)

[[-1.09058306  0.7843283 ]]

In [24]:
final_data = np.concatenate(
    [new_data_encoded[:,:1], scaled_data], axis=1
)
print(final_data)

[[0.0 -1.0905830613002285 0.7843282980120085]]

In [26]:
result = classifier.predict(final_data)
print(f'Model predicted {result}. Customer will not buy SUV')

Model predicted [0]. Customer will not buy SUV