## Random Forest

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Social_Network_Ads.csv')
data.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
# remove userID column
data = data.drop('User ID', axis= 1)
data.head()

   Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [4]:
X = data.iloc[:, :-1].values
Y = data.iloc[:, -1].values

print(X.shape)
print(Y.shape)

(400, 3)
(400,)

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=0)

print(X_train.shape)
print(X_test.shape)

(320, 3)
(80, 3)

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

CT = ColumnTransformer(
    transformers = [
        ('encoder', OneHotEncoder(drop='first', sparse=False), [0]),
        ('scaler', StandardScaler(), [1,2])
    ]
)

In [7]:
# Fit it in X_train and transform both X_train and X_test
X_train = CT.fit_transform(X_train)
X_test = CT.transform(X_test)

c:\Users\gusai\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

### Train RandomForest

In [8]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
classifier.fit(X_train, Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [9]:
y_pred = classifier.predict(X_test)

In [10]:
result = np.concatenate(
    (y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test), 1)),
    axis = 1
)

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
print('Confusion matrix\n',confusion_matrix(Y_test, y_pred))
print('\nAccuracy Score\n',accuracy_score(Y_test, y_pred))

Confusion matrix
 [[54  4]
 [ 3 19]]

Accuracy Score
 0.9125